### PR TITLE
Pieter/bugfix/swift_conn

### PR DESCRIPTION
**Pull request by forkerino**

### CODE REVIEW

**Comment by tino** [comment]
This what we're trying to fix right?
image

I don't think that is the solution. The `.url` can be None ([see here in swiftclient](https://github.com/openstack/python-swiftclient/blob/master/swiftclient/client.py#L1646)) and will only be properly set if [.get_auth()](https://github.com/openstack/python-swiftclient/blob/master/swiftclient/client.py#L1670) is called. So I think it makes more sense to check this before [199](https://github.com/solarmonkey/django-storage-swift/blob/master/swift/storage.py#L199) in the `swift_conn` property.

**Comment by forkerino** [comment]
As I read it, getting the swift_conn prop will start up the connection, and check the container, which does a [self.head_container](https://github.com/openstack/python-swiftclient/blob/606951c736cde79418e9ebcd790c4af3686a2170/swiftclient/client.py#L1805), which calls [_retry](https://github.com/openstack/python-swiftclient/blob/606951c736cde79418e9ebcd790c4af3686a2170/swiftclient/client.py#L1718), which in turn calls get_auth() (line 1727). 

How can we await the url to be available? 

Or do you mean we instead return something else in the swift_conn property?

**Comment by tino** [comment]
All the code is synchronous right? So I'm not sure how the [returned connection](https://github.com/solarmonkey/django-storage-swift/blob/master/swift/storage.py#L199) can have no url. I suspect it is a stale connection?

I think just checking that connection object has a non-`None` `.url` before returning it – and otherwise resetting/connecting – would be the solution.

**Comment by forkerino** [comment]
When I build the backend with this commit, I haven't been able to reproduce the error, btw. While I did get the error locally when I used the previous commit hash in the requirements.txt.

**Comment by tino** [comment]
OK. But are all the lines necessary? Does the assert ever evaluate to false?

NB if you want to test swiftly you can vim edit the file inside the container and then reload django so you don't have to rebuild all the time

**Comment by forkerino** [comment]
Thanks for the tip with using vim in the container. I still have it open inside a tmux window without being able to get out of it, but in a normal terminal window it worked. :')

Yes, you are right, just a simple check in the `if` works AFAICS (tried many times to get some elements, where I would normally get the error, and I don't see it popping up).

**Comment by forkerino** [comment]
@tino is this ok? 

doing `self.swift_conn` in the `if` makes sure we have a connection in case it didn't exist before.

**Comment by tino** [comment]
Let's try it!

**Pull request merged**
